server:
  port: 8080

logging:
  level:
    root: DEBUG

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://192.168.1.9:3306/cooking_master_backend?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT
      username: root
      password: 123456
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: dsa

leonardo:
  filepath:
    image: /Users/leo/Temp/image/
    video: /Users/leo/Temp/video/